# FLUX.1-dev Complete Setup for Fooocus Plus
# 
# This configuration provides everything needed to run FLUX.1-dev models
# including the main model, VAE, and text encoders.
#
# IMPORTANT: Requires HF_TOKEN environment variable for gated models

# FLUX.1-dev checkpoint (main model)
[models.checkpoints]
flux1-dev = { source = "huggingface", repo = "black-forest-labs/FLUX.1-dev", file = "flux1-dev.safetensors", gated = true }

# Alternative: FLUX.1-schnell (Apache 2.0 license, no gating)
# flux1-schnell = { source = "huggingface", repo = "black-forest-labs/FLUX.1-schnell", file = "flux1-schnell.safetensors" }

# FLUX VAE (required)
[models.vae]
flux-vae = { source = "huggingface", repo = "black-forest-labs/FLUX.1-dev", file = "ae.safetensors", gated = true }

# Text encoders (required for FLUX)
[models.text_encoder]
# CLIP-L encoder
clip_l = { source = "huggingface", repo = "comfyanonymous/flux_text_encoders", file = "clip_l.safetensors" }

# T5 XXL encoder (FP8 quantized for lower VRAM)
t5xxl_fp8 = { source = "huggingface", repo = "comfyanonymous/flux_text_encoders", file = "t5xxl_fp8_e4m3fn.safetensors" }

# Optional: Full precision T5 XXL (higher quality but requires more VRAM)
# t5xxl_fp16 = { source = "huggingface", repo = "comfyanonymous/flux_text_encoders", file = "t5xxl_fp16.safetensors" }